# Generated by Django 5.2.4 on 2025-07-14 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assets_used', models.ManyToManyField(blank=True, to='core.asset')),
                ('assigned_engineers', models.ManyToManyField(blank=True, to='core.engineer')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('Info', 'Info'), ('Caution', 'Caution'), ('Severe', 'Severe'), ('Critical', 'Critical')], max_length=20)),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mission')),
            ],
        ),
    ]
